config/routes.rb
Rails.application.routes.draw do
	root 'posts#index', as: 'home'

	get 'about' => 'pages#about', as: 'about'	

	resources :posts

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
						length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About us';
		@content = 'I am Arvik';
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]
  	include SmartListing::Helper::ControllerExtensions
  	helper  SmartListing::Helper

	def index
		posts_scope = Post.all
		posts_scope = posts_scope.like(params[:filter]) if params[:filter]
		smart_listing_create :posts, posts_scope, partial: "posts/list"
	
	end

	def show

		@post = Post.find(params[:id])

	end

	def new
		@post = Post.new
	end

	def create

		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private
	def set_post
      @post = Post.find(params[:id])
    end

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default">
  <a class="navbar-brand" href="#">SimpleBlog</a>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home",home_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Create Post",new_post_path %></li>
    </ul>  
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> 
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
 <!--      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>
<div class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/_list.html.erb
<h1>Blog Posts</h1>
<div class="postlist">
  <% unless smart_listing.empty? %>
  <div class="panel-group" id="accordion">
      <% smart_listing.collection.each do |post| %>
  <div class="well">
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
  </div>
  <% end %>
  </div>
    <%= smart_listing.paginate %>
    <%= smart_listing.pagination_per_page_links %>
    <% else %>
      <p class="alert alert-info">No records!</p>
    <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><% msg %></div>
		<% end %>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form_control'}) %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/index.html.erb
<%= smart_listing_controls_for(:posts, {class: "form-inline text-right"}) do %>
  <div class="form-group filter input-append">
    <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off %>
  </div>
  <button class="btn btn-primary disabled" type="<%= :submit %>">
    <span class="glyphicon glyphicon-search"></span>
  </button>
<%end%>
<%= smart_listing_render(:posts) %>

app/views/posts/index.js.erb
<%= smart_listing_update(:posts) %>

app/views/posts/new.html.erb
<h1>Add post</h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><% msg %></div>
		<% end %>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field(:title, {:class => 'form_control'}) %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/posts/show.html.erb
<h2><%=@post.title %></h2>
<p><%=@post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), 
				method: :delete,
				data: {confirm: 'Are you sure?'},
				:class => 'btn btn-danger' %>

app/views/smart_listing/_action_custom.html.erb
<%# 
  Custom action.

  Available local variables:
    url
    icon
    html_options:       custom html options
-%>

<%= link_to_if(action_if, content_tag(:span, '', :class => icon, :title => title), url, html_options) %>

app/views/smart_listing/_action_delete.html.erb
<%# 
  Delete action.

  Available local variables:
    action_if:          false if action is disabled
    url:                destroy url
    icon:               icon css classes
    confirmation:       confrimation text
    title
-%>

<%= link_to_if(action_if, content_tag(:i, "", :class => icon), url, :remote => true, :class => "destroy", :method => :delete, :title => title || t("smart_listing.actions.destroy"), :data => {:confirmation => confirmation || t("smart_listing.msgs.destroy_confirmation")} ) %>

app/views/smart_listing/_action_edit.html.erb
<%# 
  Edit action.

  Available local variables:
    action_if:          false if action is disabled
    url:                edit url
    icon:               icon css classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :remote => true, :class => "edit", :title => title || t("smart_listing.actions.edit") ) %>

app/views/smart_listing/_action_show.html.erb
<%# 
  Show action.

  Available local variables:
    action_if:          false if action is disabled
    url:                show url
    icon:               icon clss classes
    title
-%>

<%= link_to_if(action_if, content_tag(:i, '', :class => icon), url, :class => "show", :title => title || t("smart_listing.actions.show") ) %>

app/views/smart_listing/_item_new.html.erb
<%# 
  New list item element (contains new item placeholder and add button).

  Available local variables:
    placeholder_classes:      classes for the main container
    new_item_action_classes:  new item action classes
    colspan              
    no_items_classes:         no items container classes
    no_items_text:            no items text displayed inside container
    new_item_button_url:      argument to link_to (new item button)
    new_item_button_classes
    new_item_button_text
    new_item_autoshow         automatically show new item placeholder
    new_item_content          new item placeholder content (usually some form)
-%>

<%= content_tag(:tr, '', :class => placeholder_classes + %w{info}, :data => {smart_listing_config.data_attributes(:autoshow) => new_item_autoshow}) do %>
  <%= new_item_content %>
<% end %>
<%= content_tag(:tr, :class => new_item_action_classes + %w{info}) do %>
  <%= content_tag(:td, :colspan => colspan) do %>
    <%= content_tag(:p, :class => no_items_classes + %w{pull-left}) do %>
      <%= no_items_text %>
    <% end %>
    <%= link_to(new_item_button_url, :remote => true, :class => new_item_button_classes + %w{btn pull-right}) do %>
      <%= content_tag(:i, '', :class => smart_listing_config.classes(:icon_new)) %>
      <%= new_item_button_text %>
    <% end %>
  <% end %>
<% end %>

app/views/smart_listing/_pagination_per_page_link.html.erb
<%# 
  Pagination single per-page link.

  Available local variables:
    page:           page number
    url:            page url (if page is not selected)
    smart_listing:  current SmartListing instance
    builder:        current builder instance
-%>

<% name = page == 0 ? t('views.pagination.unlimited') : page %>
<%= url ? link_to(name, url, :remote => smart_listing.remote?) : content_tag(:span, name) %>

app/views/smart_listing/_pagination_per_page_links.html.erb
<%# 
  Pagination per-page links.

  Available local variables:
    container_classes:  classes for the main container
    per_page_sizes:     array of available per-page sizes
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= content_tag(:div, :class => container_classes ) do %>
  <% if smart_listing.options[:paginate] && (smart_listing.count > smart_listing.page_sizes.first) %>
    <%= t('views.pagination.per_page') %>
    <% per_page_sizes.each do |p| %><%= builder.pagination_per_page_link p %><% break if p >= smart_listing.count %><% end %>
    |
  <% end %>
  <%= t('views.pagination.total') %>
  <%= content_tag(:span, smart_listing.count, :class => "count") %>
<% end %>

app/views/smart_listing/_sortable.html.erb
<%# 
  Sortable attribute listing header.

  Available local variables:
    container_classes:  classes for the main container
    url:                sortable link url
    attribute:          current attribute name
    title:              current attribute title
    order:              defines column sort order
    smart_listing:      current SmartListing instance
    builder:            current builder instance
-%>

<%= link_to url, :class => container_classes, :data => {:attr => attribute}, :remote => remote do %>
  <%= title %>
  <% if order %>
    <span class="<%= order == "asc" ? smart_listing_config.classes(:icon_sort_up) : smart_listing_config.classes(:icon_sort_down) %>"></span>
  <% else %>
    <span class="<%= smart_listing_config.classes(:icon_sort_none) %>"></span>
  <% end %>
<% end %>